### ISSUE TITLE
selectboxが動いてない問題

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/Gussuri#33]
select box を操作した際に以下のエラー
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'submitOnChanged' has not been initialized.
#0      DropBoxWidgetState.submitOnChanged (package:gussuri/component/DropBoxWidget.dart)
#1      DropBoxWidgetState.build.<anonymous closure>.<anonymous closure> (package:gussuri/component/DropBoxWidget.dart:68:19)
#2      State.setState (package:flutter/src/widgets/framework.dart:1114:30)
#3      DropBoxWidgetState.build.<anonymous closure> (package:gussuri/component/DropBoxWidget.dart:66:17)
#4      _DropdownButtonState._handleTap.<anonymous closure> (package:flutter/src/material/dropdown.dart:1323:25)
<asynchronous suspension>
```

**Comment by ayuki-joto** [comment]
これ思ったより根が深そう

**Comment by ayuki-joto** [comment]
```

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [GlobalObjectKey<TimePickerState> String#2a097] was used by multiple widgets. The parents of those widgets were:
- Align(alignment: Alignment.center, dependencies: [Directionality], renderObject: RenderPositionedBox#6aa3e relayoutBoundary=up11 NEEDS-PAINT)
- Align(alignment: Alignment.center, dependencies: [Directionality], renderObject: RenderPositionedBox#1d210 relayoutBoundary=up11 NEEDS-PAINT)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2883:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#2      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:2827:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#4      BuildOwner._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:2822:36)
#5      BuildOwner._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:2891:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2950:11)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3032:8)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#13     _invoke (dart:ui/hooks.dart:148:13)
#14     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#15     _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================
```
